a = input('Digite algo:')
print('O tipo primitivo dele é:', type(a))
print('O que você digitou é um número?', a.isnumeric())
print('É uma palavra?', a.isalpha())
print('Só contém espaços?', a.isspace())
